package it.gov.pagopa.fdr.service.model.re;

public enum FdrActionEnum {
  INFO,

  CREATE_FLOW,
  DELETE_FLOW,
  ADD_PAYMENT,
  DELETE_PAYMENT,
  PUBLISH,

  INTERNAL_CREATE_FLOW,
  INTERNAL_DELETE_FLOW,
  INTERNAL_ADD_PAYMENT,
  INTERNAL_DELETE_PAYMENT,
  INTERNAL_PUBLISH,

  GET_ALL_CREATED_FDR,
  GET_CREATED_FDR,
  GET_CREATED_FDR_PAYMENT,

  GET_ALL_FDR_PUBLISHED_BY_PSP,
  GET_FDR_PUBLISHED_BY_PSP,
  GET_FDR_PAYMENT_PUBLISHED_BY_PSP,

  GET_ALL_FDR,
  GET_FDR,
  GET_FDR_PAYMENT,
}
