# release.yml

changelog:
  exclude:
    labels:
      - skip
    authors:
      - pagopa-github-bot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - major
    - title: Exciting New Features 🎉
      labels:
        - minor
    - title: Exciting New Features 🎉
      labels:
        - minor
    - title: Other Changes
      labels:
        - "*"
