package it.gov.pagopa.fdr.service.re.model;

public enum FdrActionEnum {
  INFO,

  CREATE_FLOW,
  DELETE_FLOW,
  ADD_PAYMENT,
  DELETE_PAYMENT,
  PUBLISH,

  INTERNAL_CREATE_FLOW,
  INTERNAL_DELETE_FLOW,
  INTERNAL_ADD_PAYMENT,
  INTERNAL_DELETE_PAYMENT,
  INTERNAL_PUBLISH,

  GET_ALL_CREATED_FDR,
  GET_CREATED_FDR,
  GET_CREATED_FDR_PAYMENT,
  INTERNAL_GET_ALL_CREATED_FDR,
  INTERNAL_GET_CREATED_FDR,
  INTERNAL_GET_CREATED_FDR_PAYMENT,

  INTERNAL_GET_ALL_BY_IUV_FDR,
  INTERNAL_GET_ALL_BY_IUR_FDR,

  GET_ALL_FDR,
  GET_FDR,
  GET_FDR_PAYMENT,
  INTERNAL_GET_ALL_FDR,
  INTERNAL_GET_FDR,
  INTERNAL_GET_FDR_PAYMENT
}
