microservice-chart:
  namespace: "fdr"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-fdr
    tag: 1.0.20
    pullPolicy: Always
  readinessProbe:
    httpGet:
      path: /q/health/ready
      port: 8080
    initialDelaySeconds: 10
    failureThreshold: 10
    periodSeconds: 5
  livenessProbe:
    httpGet:
      path: /q/health/live
      port: 8080
    initialDelaySeconds: 10
    failureThreshold: 10
    periodSeconds: 5
  envConfig:
    APP_ENVIRONMENT: "uat"
    TZ: "Europe/Rome"
    OTEL_ENDPOINT: "http://otel-collector.elastic-system.svc.cluster.local:4317"
    ADAPTER_API_CONFIG_CACHE_URL: "https://api.uat.platform.pagopa.it/api-config-cache/p/v1"
    ADAPTER_API_CONFIG_CACHE_CRON: "0 */1 * * * ?"
    QUEUE_CONVERSION_NAME: "flowidsendqueue"
    EVENT_HUB_RE_NAME: "fdr-re"
    BLOB_RE_CONTAINER_NAME: "payload"
    BLOB_HISTORY_CONTAINER_NAME: "fdrhistory"
    TABLE_HISTORY_FDR_PUBLISH_TABLE: "fdrpublish"
    TABLE_HISTORY_FDR_PAYMENT_PUBLISH_TABLE: "fdrpaymentpublish"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  secretProvider:
    create: true
    envSecrets:
      ADAPTER_API_CONFIG_CACHE_API_KEY: "api-config-cache-subscription-key-string"
      OTEL_AUTH_BEARER: "otel-auth-bearer"
      MONGODB_CONNECTION_STRING: "mongodb-connection-string"
      QUEUE_CONVERSION_CONNECTION_STRING: "fdr-sa-connection-string"
      EVENT_HUB_RE_CONNECTION_STRING: "azure-event-hub-re-connection-string"
      BLOB_RE_CONNECTION_STRING: "fdr-re-sa-connection-string"
      BLOB_HISTORY_CONNECTION_STRING: "fdr-history-sa-connection-string"
      TABLE_HISTORY_CONNECTION_STRING: "fdr-history-sa-connection-string"
    keyvault:
      name: "pagopa-u-fdr-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  resources:
    requests:
      memory: "2Gi"
      cpu: "400m"
    limits:
      memory: "3Gi"
      cpu: "800m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: "75"
      - type: memory
        metadata:
          type: Utilization
          value: "75"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  serviceMonitor:
    create: true
    endpoints:
      - interval: 5s
        targetPort: 8080
        path: /q/metrics
  service:
    create: true
  ingress:
    create: true
    host: "weuuat.fdr.internal.uat.platform.pagopa.it"
    path: /pagopa-fdr-service(/|$)(.*)
  canaryDelivery:
    create: false
